### ISSUE TITLE
Scale axis based on values for readability

### ISSUE THREAD

**Issue by mah985** [mah985/Oculus-3D-Visualization-Tool#11]
Implement an algorithm for scaling the x-y-z axis appropriately for ease of reading. Ex. so that values always start in front of the camera and so that data leaps like 1 to 4000 can be seen.

**Comment by unimatrixZero1** [comment]
Actually working on this right now!

**Comment by unimatrixZero1** [comment]
Initial scaling can now be adjust with these globals:

plotInitSizeX
plotInitSizeY
plotInitSizeZ
plotPointSizeCoeff

And the camera starts in a reasonable position now that trackballControls.js is merged.
