### ISSUE TITLE
Point selection cleared when VRGUI is touched

### ISSUE THREAD

**Issue by skiskow** [mah985/Oculus-3D-Visualization-Tool#115]
On click in pointSelection.js is clearing the selected points when the vr menu is interacted with, not sure if this going to cause issues in vr or only in browser. But a thing never the less.

**Comment by seaboyern** [comment]
This is because currently when you click off of a point, point selection is cleared in the browser only. It was more of a placeholder for testing. Should be very easily fixed.

**Comment by skiskow** [comment]
Fixed in most current branch
