### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by mah985** [mah985/Oculus-3D-Visualization-Tool#132]
If the user is not logged in and attempts to goto the dashboard, the page will just infinity load. We need a prompt that takes the user to the login page or a warning.

**Comment by mah985** [comment]
@Wynston if you have time to look at this one

**Comment by Wynston** [comment]
Should be good now. Automatically checks if the user isn't signed in and is on the dashboard page. Redirects that user to the home page.
