### ISSUE TITLE
CSV loading

### ISSUE THREAD

**Issue by seaboyern** [mah985/Oculus-3D-Visualization-Tool#17]
- [x] When loading a .csv file that is over the size limit, axis selection is not positioned correctly in the browser
- [x] No feedback when .csv file is too large. Still allows you to select axes
<img width="1218" alt="screen shot 2018-02-03 at 4 15 38 pm" src="https://user-images.githubusercontent.com/32285238/35780726-6054ae40-09a5-11e8-96f1-255081bb8682.png">

- [x] remote load allows you to load no url
<img width="936" alt="screen shot 2018-02-04 at 12 18 59 pm" src="https://user-images.githubusercontent.com/32285238/35780752-9c031af8-09a5-11e8-8e33-56ad2f5216b7.png">

**Comment by mah985** [comment]
Should be fixed in the new dashboard set up. Please close if you can verify that it is.

**Comment by seaboyern** [comment]
Different system being used. No longer relevant.
