### ISSUE TITLE
It is possible to be upside down in the space

### ISSUE THREAD

**Issue by seaboyern** [mah985/Oculus-3D-Visualization-Tool#20]
in a browser, when turning the world around it is possible to be upside down in the space
![upsidedown](https://user-images.githubusercontent.com/32285238/35780979-349be210-09a9-11e8-89d4-75c8aa4b2119.gif)

**Comment by mah985** [comment]
Just the type of controls that we are using. Not a bug just how the controls are made by threejs. We can use other controls if we have time in the future.

**Comment by seaboyern** [comment]
Thought so. Won't worry about it then.
