### ISSUE TITLE
Add More Party Parrot Emojis

### ISSUE THREAD

**Issue by masterSmallwood** [mah985/Oculus-3D-Visualization-Tool#30]
We are seriously lacking in party-parrot emojis. Studies have shown that a team's success is directly proportional to the amount of party-parrot emojis available in their slack channels.

**Comment by mah985** [comment]
This is now our teams primary focus for Deliverable-2. All devs drop everything else

**Comment by mah985** [comment]
![angelparrot](https://user-images.githubusercontent.com/32170342/36293654-0162e51e-12a1-11e8-881a-7f3fe30b8206.gif)
![angryparrot](https://user-images.githubusercontent.com/32170342/36293655-0179e4e4-12a1-11e8-9361-9f7393eb92eb.gif)
![aussiecongaparrot](https://user-images.githubusercontent.com/32170342/36293656-01917000-12a1-11e8-9a47-d9022922ec08.gif)
![aussieparrot](https://user-images.githubusercontent.com/32170342/36293657-01a9bf0c-12a1-11e8-90e3-ade13bce3da0.gif)
![aussiereversecongaparrot](https://user-images.githubusercontent.com/32170342/36293658-01c0cdc8-12a1-11e8-801b-d114d0ffab36.gif)
![bananaparrot](https://user-images.githubusercontent.com/32170342/36293659-01d99db2-12a1-11e8-85f7-ed030754b24d.gif)
![beretparrot](https://user-images.githubusercontent.com/32170342/36293660-01f0859a-12a1-11e8-84d4-89f3afca546d.gif)
![blondesassyparrot](https://user-images.githubusercontent.com/32170342/36293661-02080698-12a1-11e8-9c66-37dd20936ea7.gif)
![bluescluesparrot](https://user-images.githubusercontent.com/32170342/36293662-02205090-12a1-11e8-9704-1ef60cd25eda.gif)
![boredparrot](https://user-images.githubusercontent.com/32170342/36293663-0235e3f6-12a1-11e8-8582-2171851b4692.gif)
![ceilingparrot](https://user-images.githubusercontent.com/32170342/36293664-024c0190-12a1-11e8-993f-3a3387642e9a.gif)
![chillparrot](https://user-images.githubusercontent.com/32170342/36293665-0262006c-12a1-11e8-9b79-3cfbc53a8663.gif)
![christmasparrot](https://user-images.githubusercontent.com/32170342/36293666-02783800-12a1-11e8-8d0c-44072ae8ba96.gif)
![coffeeparrot](https://user-images.githubusercontent.com/32170342/36293667-028eaf5e-12a1-11e8-9722-2b1255a773b7.gif)
![confusedparrot](https://user-images.githubusercontent.com/32170342/36293668-02a4bfe2-12a1-11e8-8bc9-7b78c9824bef.gif)
![congaparrot](https://user-images.githubusercontent.com/32170342/36293669-02b98756-12a1-11e8-9334-468044b205f4.gif)
![congapartyparrot](https://user-images.githubusercontent.com/32170342/36293670-02ce4ca4-12a1-11e8-9124-b4bebfec43b0.gif)
![darkbeerparrot](https://user-images.githubusercontent.com/32170342/36293671-02e8b1fc-12a1-11e8-8971-cc689062cdeb.gif)
![dealwithitparrot](https://user-images.githubusercontent.com/32170342/36293672-02fe1c7c-12a1-11e8-8d19-8db79618eedf.gif)
![dreidelparrot](https://user-images.githubusercontent.com/32170342/36293673-03136e06-12a1-11e8-99a6-514b60b09be0.gif)
![evilparrot](https://user-images.githubusercontent.com/32170342/36293674-0329949c-12a1-11e8-9e3d-46788e9d1b9b.gif)
![explodyparrot](https://user-images.githubusercontent.com/32170342/36293675-0344c5e6-12a1-11e8-81d4-79c6028fc005.gif)
![fastparrot](https://user-images.githubusercontent.com/32170342/36293676-0362ca14-12a1-11e8-9bb3-6ceb5bef96d9.gif)
![fidgetparrot](https://user-images.githubusercontent.com/32170342/36293677-037d7ea4-12a1-11e8-864c-2f84500088cd.gif)
![fiestaparrot](https://user-images.githubusercontent.com/32170342/36293678-039d2be6-12a1-11e8-86ce-b535f3a5c04e.gif)
![gentlemanparrot](https://user-images.githubusercontent.com/32170342/36293680-03b3df1c-12a1-11e8-955a-4dd3895231eb.gif)
![gothparrot](https://user-images.githubusercontent.com/32170342/36293682-03ca6e62-12a1-11e8-9ca6-becc1b837c57.gif)
![halalparrot](https://user-images.githubusercontent.com/32170342/36293683-03e14916-12a1-11e8-969c-34947617aef3.gif)
![hamburgerparrot](https://user-images.githubusercontent.com/32170342/36293684-03f70ad0-12a1-11e8-975f-4038f9ebbd7f.gif)
![harrypotterparrot](https://user-images.githubusercontent.com/32170342/36293685-04107a2e-12a1-11e8-8cf0-1a0e6bbb8b8b.gif)
![ice-cream-parrot](https://user-images.githubusercontent.com/32170342/36293686-042ccb34-12a1-11e8-8538-9248d04566ba.gif)
![invisibleparrot](https://user-images.githubusercontent.com/32170342/36293687-0443baf6-12a1-11e8-88e3-8fe822883590.gif)
![loveparrot](https://user-images.githubusercontent.com/32170342/36293688-045da70e-12a1-11e8-93a4-45c29a0afea0.gif)
![luckyparrot](https://user-images.githubusercontent.com/32170342/36293689-0473108a-12a1-11e8-9892-751d7ee30cca.gif)
![margaritaparrot](https://user-images.githubusercontent.com/32170342/36293690-048e50c0-12a1-11e8-8fda-c0780d962496.gif)
![matrixparrot](https://user-images.githubusercontent.com/32170342/36293692-04a56256-12a1-11e8-9313-3773466f648d.gif)
![middleparrot](https://user-images.githubusercontent.com/32170342/36293693-04ba9fae-12a1-11e8-88de-2f12c1278fcc.gif)
![moonwalkingparrot](https://user-images.githubusercontent.com/32170342/36293694-04d043ae-12a1-11e8-9806-f866678299da.gif)
![oldtimeyparrot](https://user-images.githubusercontent.com/32170342/36293695-04e6aaea-12a1-11e8-994e-b40b7d728a19.gif)
![papalparrot](https://user-images.githubusercontent.com/32170342/36293696-04fddde6-12a1-11e8-9172-02f6155ab483.gif)
![parrot](https://user-images.githubusercontent.com/32170342/36293697-051499d2-12a1-11e8-9f2a-ea4147ad7a5c.gif)
![parrotbeer](https://user-images.githubusercontent.com/32170342/36293698-052fb578-12a1-11e8-8199-a463816df2d8.gif)
![parrotcop](https://user-images.githubusercontent.com/32170342/36293699-0544eac4-12a1-11e8-914d-e05d3bfe7bcb.gif)
![parrotdad](https://user-images.githubusercontent.com/32170342/36293700-0559f568-12a1-11e8-9565-81f33af84d00.gif)
![parrotmustache](https://user-images.githubusercontent.com/32170342/36293701-056fbc5e-12a1-11e8-938a-9c38209ded31.gif)
![parrotsleep](https://user-images.githubusercontent.com/32170342/36293702-05856f68-12a1-11e8-8bdc-c8a940218b48.gif)
![parrotwave1](https://user-images.githubusercontent.com/32170342/36293703-059aa112-12a1-11e8-9f3c-38aaadd7a373.gif)
![parrotwave2](https://user-images.githubusercontent.com/32170342/36293704-05b01a92-12a1-11e8-97fd-becfbe565752.gif)
![parrotwave3](https://user-images.githubusercontent.com/32170342/36293705-05c44a9e-12a1-11e8-8281-b9c826c06215.gif)
![parrotwave4](https://user-images.githubusercontent.com/32170342/36293706-05db5932-12a1-11e8-8635-79d3645f93ae.gif)
![parrotwave5](https://user-images.githubusercontent.com/32170342/36293707-05f1d05e-12a1-11e8-89b9-9cb6635d5a6b.gif)
![parrotwave6](https://user-images.githubusercontent.com/32170342/36293708-0608c1a6-12a1-11e8-892c-347789a8d519.gif)
![parrotwave7](https://user-images.githubusercontent.com/32170342/36293709-061d71d2-12a1-11e8-9a1f-0cade5a6d153.gif)
![partyparrot](https://user-images.githubusercontent.com/32170342/36293710-063241fc-12a1-11e8-95a0-f01855fc5e74.gif)
![pizzaparrot](https://user-images.githubusercontent.com/32170342/36293711-06479de0-12a1-11e8-919c-b73486abc25c.gif)
![prideparrot](https://user-images.githubusercontent.com/32170342/36293712-065dcbf6-12a1-11e8-8f43-4c048354a411.gif)
![reversecongaparrot](https://user-images.githubusercontent.com/32170342/36293713-067776aa-12a1-11e8-965f-2f3888ce7dc1.gif)
![rightparrot](https://user-images.githubusercontent.com/32170342/36293715-068dcde2-12a1-11e8-8859-1f4ec473e565.gif)
![rotatingparrot](https://user-images.githubusercontent.com/32170342/36293716-06a30e6e-12a1-11e8-8803-e4259b473342.gif)
![ryangoslingparrot](https://user-images.githubusercontent.com/32170342/36293717-06ba0330-12a1-11e8-9e3c-19874551a992.gif)
![sadparrot](https://user-images.githubusercontent.com/32170342/36293718-06d371a8-12a1-11e8-9cb7-3b09418d89f1.gif)
![sassyparrot](https://user-images.githubusercontent.com/32170342/36293719-06e932cc-12a1-11e8-8e1f-3da117ab8525.gif)
![scienceparrot](https://user-images.githubusercontent.com/32170342/36293720-07057cc0-12a1-11e8-9cb2-c6753de36f75.gif)
![shipitparrot](https://user-images.githubusercontent.com/32170342/36293721-071e8e90-12a1-11e8-8d40-f0a4409b5b6a.gif)
![shufflefurtherparrot](https://user-images.githubusercontent.com/32170342/36293723-073390ce-12a1-11e8-965f-483efd66c727.gif)
![shuffleparrot](https://user-images.githubusercontent.com/32170342/36293724-07486774-12a1-11e8-8f3f-e454f23fc223.gif)
![shufflepartyparrot](https://user-images.githubusercontent.com/32170342/36293725-075d8906-12a1-11e8-980c-1be275c124ab.gif)
![skiparrot](https://user-images.githubusercontent.com/32170342/36293726-07741c0c-12a1-11e8-8bd5-9a567c5bdd17.gif)
![slomoparrot](https://user-images.githubusercontent.com/32170342/36293727-078a902c-12a1-11e8-9ade-31244929e099.gif)
![slowparrot](https://user-images.githubusercontent.com/32170342/36293728-07a0eaca-12a1-11e8-8d14-2aef15bcbbd7.gif)
![stableparrot](https://user-images.githubusercontent.com/32170342/36293729-07b6b6b6-12a1-11e8-90ba-78d5c0361c93.gif)
![stalkerparrot](https://user-images.githubusercontent.com/32170342/36293730-07cdfdf8-12a1-11e8-8356-edb10df0266e.gif)
![tacoparrot](https://user-images.githubusercontent.com/32170342/36293731-07e30c34-12a1-11e8-869e-7a3951f94b25.gif)
![thumbsupparrot](https://user-images.githubusercontent.com/32170342/36293732-07f87588-12a1-11e8-8a43-ac93ff70bcee.gif)
![tripletsparrot](https://user-images.githubusercontent.com/32170342/36293733-080df336-12a1-11e8-89c9-acab0158f8e7.gif)
![twinsparrot](https://user-images.githubusercontent.com/32170342/36293734-0823c1a2-12a1-11e8-80f7-4649c97f00e7.gif)
![ultrafastparrot](https://user-images.githubusercontent.com/32170342/36293735-08392150-12a1-11e8-8bcb-39b5ba1ea506.gif)
![upvotepartyparrot](https://user-images.githubusercontent.com/32170342/36293736-084e14e8-12a1-11e8-885e-446e133b428d.gif)

**Comment by mah985** [comment]
Issue will now be closed unless others have more to add

**Comment by masterSmallwood** [comment]
Until they are all in the slack channel, this issue WILL remain open.
