### ISSUE TITLE
Firebase: User authentication warning

### ISSUE THREAD

**Issue by seaboyern** [mah985/Oculus-3D-Visualization-Tool#81]
When loading any world while signed in through google:

<img width="1261" alt="screen shot 2018-03-04 at 4 36 06 pm" src="https://user-images.githubusercontent.com/32285238/36952911-50f072a8-1fdb-11e8-9150-96ab67cda3fc.png">

**Comment by Wynston** [comment]
Got a potential fix to the issue on the 'Development-Wynston' branch. I'm unsure of how to reproduce the error but I made sure that before the function was called that the 'profile variable' was set to the signed in google users info.
