### ISSUE TITLE
Fix point sizing for all sizes of data sets

### ISSUE THREAD

**Issue by seaboyern** [mah985/Oculus-3D-Visualization-Tool#9]
In the current implementation of points using vertex shaders (yet to be merged into Development from Davidson-Development), using a .csv with a "smaller" amount of points clouds the readability of the set. 

<img width="1035" alt="screen shot 2018-02-02 at 5 55 34 pm" src="https://user-images.githubusercontent.com/32285238/35759942-7904fbac-0842-11e8-84a2-42c285250978.png">

Taken using a randomly generated .csv with 1000 points.

**Comment by unimatrixZero1** [comment]
Added a global variable for the scaling coefficient of the points. 

var plotPointSizeCoeff = 0.01;

So this effectively sets the dimensions of the point sprite to be 1% of the distance from 0 to the largest entry in the largest axis. So now the points should look the same on all datasets.
