### ISSUE TITLE
Site centering

### ISSUE THREAD

**Issue by seaboyern** [mah985/Oculus-3D-Visualization-Tool#98]
Adding the logo to the site pushed the dashboard over so it is no longer centered. 

![screen shot 2018-03-17 at 3 07 11 pm](https://user-images.githubusercontent.com/32285238/37559962-e818806c-29f4-11e8-9ba5-a055fb827848.png)

**Comment by Wynston** [comment]
![dashboard](https://user-images.githubusercontent.com/23458594/37680182-be5ff862-2c48-11e8-8540-299a9d1387ca.PNG)

Is it browser dependent or a caching issue? I used absolute positioning so it shouldn't be pushing any element over.
